version: 0.2

env:
  variables:
    S3_BUCKET: "angular-bucket-1234"
    BUILD_FOLDER: "dist/my-angular-project"
    ZIP_NAME: "angular-build.zip"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@19.2.7

  build:
    commands:
      - echo Build started on `date`
      - node -v
      - npm -v
      - ng build
      - echo Build completed…

  post_build:
    commands:
      - echo Preparing deployment package...
      - mkdir deploy
      - cp -r $BUILD_FOLDER/* deploy/
      - cp appspec.yml deploy/
      - cp install_nginx.sh deploy/
      - cd deploy
      - zip -r ../$ZIP_NAME .
      - cd ..
      - echo Uploading $ZIP_NAME to S3 bucket $S3_BUCKET...
      - aws s3 cp $ZIP_NAME s3://$S3_BUCKET/$ZIP_NAME

artifacts:
  files:
    - angular-build.zip